version: "3.6"

services:

  db:
    image: "postgres:11"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: django-jobs
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - ALLOWED_HOSTS
      - DATABASE_URL
      - DJANGO_DEBUG
      - SECRET_KEY
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - django-media:/src/media
      - django-static:/src/static

volumes:
  django-media:
  django-static:
  postgres_data:
